import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
     
      <body className=" bg-slate-900">
        {children}
      <ToastContainer
  closeButton={true}       // show close button
  closeOnClick={true}      // close when clicking on the toast itself
  draggable={true}        
  theme="dark" // allow drag to dismiss
  pauseOnHover={true}      // pause auto-close on hover
  autoClose={3000}         // auto close after 5 seconds (adjust as needed)
/>

      </body>
    </html>
  );
}
